title: FAIR Lesson Plan Handbook
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://elixir-europe-training.github.io/ELIXIR-TrP-FAIR-Converge"

# Build settings
remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@3.2.0
theme_color: 0c3450
permalink: pretty

plugins:
  - elixir-toolkit-theme-plugins
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
  - jemoji
  - webrick

collections:
  pages:
    output: true
    permalink: /:path/
  lesson-plans:
    output: true
    permalink: /units/:path/

include:
  - _pages

exclude:
  - docs/
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/